import { convertedStatesOption } from "./formPickupAddress";
export const FormBillingAddress = [
  [
    {
      key: "CompanyName",
      dataTestid: "billing-address-company-name",
      label: "Company name",
      placeholder: "e.g. John Smith",
      type: "input",
    },
    {
      key: "Phone",
      dataTestid: "billing-address-contact",
      label: "Contact",
      placeholder: "e.g. 281-259-2402",
      value: "",
      scaleSpan: 12,
    },
  ],
  [
    {
      key: "StreetAddress",
      dataTestid: "billing-address-street-address",
      label: "Street address",
      placeholder: "e.g. 2700 Greens Rd",
      value: "",
      type: "input",
      scaleSpan: 24,
      isRequired: true,
    },
  ],
  [
    {
      key: "MoreAddress",
      dataTestid: "billing-address-apartment",
      label: "Apartment, Suite, Building",
      placeholder: "e.g. Door 27, Floor 4",
      type: "input",
      scaleSpan: 24,
    },
  ],
  [
    {
      key: "Country",
      dataTestid: "billing-address-country",
      label: "Country",
      placeholder: "",
      value: "USA",
      scaleSpan: 12,
      type: "input",
      isDisable: true,
    },
    {
      key: "State",
      dataTestid: "billing-address-state",
      label: "State",
      placeholder: "Choose a state",
      options: convertedStatesOption,
      value: "",
      type: "selection",
      isRequired: true,
    },
  ],
  [
    {
      key: "City",
      dataTestid: "billing-address-city",
      label: "City",
      placeholder: "Choose a city",
      value: "",
      type: "input",
      isRequired: true,
    },
    {
      key: "PostalCode",
      dataTestid: "billing-address-postal-code",
      label: "Postal Code",
      placeholder: "e.g. SC456",
      value: "",
      type: "input",
      scaleSpan: 12,
      isRequired: true,
    },
  ],
  [
    {
      key: "EmailAddress",
      dataTestid: "billing-address-email",
      label: "Email",
      placeholder: "e.g. johnsmith@example.com",
      value: "",
      type: "input",
    },
    {
      key: "Fax",
      dataTestid: "billing-address-fax",
      label: "Fax",
      placeholder: "e.g. 281-259-2402",
      value: "",
      type: "input",
      scaleSpan: 12,
    },
  ],
  [
    {
      key: "checkBilling",
      dataTestid: "billing-address-checkbox-default-billing",
      label: "Set as default Billing Address for account",
      placeholder: "",
      value: true,
      type: "checkbox",
      scaleSpan: 24,
    },
  ],
];
