import moment from "moment";
import { exportUserInfo } from "./ultils";
const mockdata = [
  {
    "@UserGUID": "{316BD48A-1105-4577-93D3-82553E819C06}",
    "@OrderID": "6842",
    "@SiteID": "1",
    "@SiteCode": "Corporate",
    "@OrderNumber": "6842",
    "@OrderStatus": "X",
    "@CustomerID": "107",
    "@CreateDate": "8/22/2022 9:34:00 PM",
    "@CreateDateDate": "08/22/2022",
    "@CreateUserName": "automationtest",
    "@OrderDate": "8/22/2022",
    "@ServiceDesc": "Regular",
    "@AbbrService": "Regular",
    "@Service": "Regular",
    "@VehicleType": "Any",
    "@VehicleTypeID": "1",
    "@PodSendType": "1",
    "@Auth": "awb-num",
    "@AmountQuote": "$0.00",
    "@Caller": "Ruth",
    "@CallerPhone": "482.898.7713 x665",
    "@InvoiceBatchID": "0",
    "@AmountCharged": "$150.00",
    "@AmountReceived": "$0.00",
    "@PriorityGroup": "1",
    "@AutoVerify": "True",
    "@OrderMainType": "R",
    "@OrderGUID": "{5E336733-CD46-4FE3-BEE7-F8BF208BF56F}",
    "@PackageTypeID": "0",
    "@CarrierTypeID": "1",
    "@LastChanged": "8/22/2022 11:35:07 PM",
    "@Origin": "P",
    "@OperationalStatus": "V",
    "@DimWeightFactor": "0",
    "@TotalMiles": "15.41",
    "@CallerEmail": "Marc59@yahoo.com",
    "@DueDateTime": "8/23/2022 12:34:00 AM",
    "@HolidayNameID": "0",
    "@IncludeHolidayNameID": "0",
    "@DueTimeHolidayNameID": "0",
    "@AmountChargedFlag": "0",
    "@CurrentTime": "12/16/2022 7:28:17 AM",
    "@OrderFileCount": "0",
    Stops: {
      Stop: [
        {
          "@OrderStopID": "14061",
          "@Sequence": "1",
          "@StopType": "P",
          "@ScheduledDateTime": "8/22/2022 9:34:00 PM",
          "@TimeOfServiceCode": "WN",
          "@DispatchGroupID": "-1",
          "@StopMiles": "15.41",
          "@ZLatitude": "39.534091",
          "@ZLongitude": "-107.776113",
          "@StopID": "16578",
          "@DispatchZone": "81650",
          "@Name": "Kathryn Senor Elementary School",
          "@Address": "652 E 5th St",
          "@City": "CO",
          "@State": "CO",
          "@Zip": "81650",
          "@Country": "USA",
          "@Phone": "+12137402805",
          "@See": "Mr Auto",
          "@Room": "Master",
          "@Latitude": "39.534091",
          "@Longitude": "-107.776113",
          "@LocationTypeID": "1",
          "@AVSQuality": "1",
          "@ScheduledDateTimeTZ": "MST",
          OrderStopPieces: null,
        },
        {
          "@OrderStopID": "14062",
          "@Sequence": "2",
          "@StopType": "D",
          "@ScheduledDateTime": "8/23/2022 12:34:00 AM",
          "@TimeOfServiceCode": "0",
          "@DispatchGroupID": "-1",
          "@ZLatitude": "39.568629",
          "@ZLongitude": "-107.517256",
          "@StopID": "16579",
          "@DispatchZone": "81647",
          "@Name": "McDonald",
          "@Address": "811 Castle Valley Blvd",
          "@City": "CO",
          "@State": "CO",
          "@Zip": "81647",
          "@Country": "USA",
          "@Phone": "+3750965",
          "@See": "Mr Auto",
          "@Room": "Master",
          "@Latitude": "39.568629",
          "@Longitude": "-107.517256",
          "@LocationTypeID": "1",
          "@AVSQuality": "1",
          "@ScheduledDateTimeTZ": "MST",
          OrderStopPieces: null,
        },
      ],
    },
    OrderFees: {
      OrderFee: {
        "@Sequence": "1",
        "@FeeAmount": "$150.00",
        "@FeeValue": "Zone1=&Zone2=&Mile1=15.41&TotalDistance=15.41&",
        "@OverrideFlag": "False",
        "@SubSequence": "0",
        "@RateID": "449",
        "@RateName": "Dir-Dft",
        "@RateIDFix": "False",
        "@FeeValueOverrideFlag": "False",
        "@FeeTitle": "Service",
        "@FeeCode": "SV",
      },
    },
    Jobs: {
      Job: {
        "@JobID": "6800",
        "@Sequence": "1",
        "@JobNumber": "6842",
        "@JobStatus": "X",
        "@SiteID": "1",
        "@Service": "Regular",
        "@VehicleTypeID": "1",
        "@SplitPercentage": "50",
        "@JobDate": "8/22/2022",
        "@DispatchGroupID": "37",
        "@DispatchGroupOverride": "1",
        "@DeliverySequence": "1",
        "@JobModeID": "1",
        Drivers: {
          Driver: [
            { "@Sequence": "1", "@DriverBaseAmountOverride": "False" },
            { "@Sequence": "2", "@DriverBaseAmountOverride": "False" },
          ],
        },
        JobStops: {
          JobStop: [
            {
              "@PodRequired": "False",
              "@JobStopID": "14540",
              "@Sequence": "1",
              "@JobStopStatus": "X",
              "@StopType": "P",
              "@ScheduledDateTime": "8/22/2022 9:34:00 PM",
              "@ZLatitude": "39.534091",
              "@ZLongitude": "-107.776113",
              "@StopID": "16578",
              "@DispatchZone": "81650",
              "@Name": "Kathryn Senor Elementary School",
              "@Address": "652 E 5th St",
              "@City": "CO",
              "@State": "CO",
              "@Zip": "81650",
              "@Country": "USA",
              "@Phone": "+12137402805",
              "@See": "Mr Auto",
              "@Room": "Master",
              "@Latitude": "39.534091",
              "@Longitude": "-107.776113",
              "@LocationTypeID": "1",
              "@AVSQuality": "1",
              JobStopPieces: null,
            },
            {
              "@PodRequired": "False",
              "@JobStopID": "14541",
              "@Sequence": "2",
              "@JobStopStatus": "X",
              "@StopType": "D",
              "@ScheduledDateTime": "8/23/2022 12:34:00 AM",
              "@ZLatitude": "39.568629",
              "@ZLongitude": "-107.517256",
              "@StopID": "16579",
              "@DispatchZone": "81647",
              "@Name": "McDonald",
              "@Address": "811 Castle Valley Blvd",
              "@City": "CO",
              "@State": "CO",
              "@Zip": "81647",
              "@Country": "USA",
              "@Phone": "+3750965",
              "@See": "Mr Auto",
              "@Room": "Master",
              "@Latitude": "39.568629",
              "@Longitude": "-107.517256",
              "@LocationTypeID": "1",
              "@AVSQuality": "1",
              JobStopPieces: null,
            },
          ],
        },
      },
    },
    OrderFrequencies: null,
    OrderNotifies: {
      OrderNotify: [
        {
          "@Sequence": "1",
          "@CustomerNotifyID": "",
          "@NotifyEventTypeID": "-1",
          "@StyleSheetID": "33",
          "@FromEmail": "helpdesk@e-courier.com",
          "@NotifyEmail": "Marc59@yahoo.com",
          "@Subject": "$OrderNumber $AmountCharged",
          "@NotifyDateTime": "8/22/2022 10:34:05 PM",
        },
        {
          "@Sequence": "2",
          "@CustomerNotifyID": "",
          "@NotifyEventTypeID": "2",
          "@StyleSheetID": "54",
          "@FromEmail": "Helpdesk@e-courier.com",
          "@NotifyEmail": "LastStopEmail",
          "@Subject": "Order $OrderNumber has been delivered.",
          "@NotifyDateTime": "",
        },
        {
          "@Sequence": "3",
          "@CustomerNotifyID": "",
          "@NotifyEventTypeID": "102",
          "@StyleSheetID": "55",
          "@FromEmail": "helpdesk@e-courier.com",
          "@NotifyEmail": "buddy@e-courier.com",
          "@Subject": "",
          "@NotifyDateTime": "",
        },
      ],
    },
    OrderFiles: null,
    Site: {
      "@SiteID": "1",
      "@CompanyID": "999",
      "@SiteCode": "Corporate",
      "@SiteType": "C",
      "@Name": "TEST Company",
      "@DBAName": "e-Courier Test Company",
      "@Address": "123 LoneStar Dr",
      "@City": "Houston",
      "@State": "Tx",
      "@Zip": "77002",
      "@Country": "USA",
      "@Phone": "281-812-3762",
      "@EMail": "buddy@e-courier.com",
      "@Contact": "Buddy",
      "@WebURL": "budtest.e-courier.com",
      "@Message":
        "The Site created for testing your ideas.  Let us know if any questions - buddy@e-courier.com",
      "@ARAccountNumber": "1200",
      "@ARDeptNumber": "1",
      "@APAccountNumber": "1200",
      "@APDeptNumber": "1",
      "@BankAccountNumber": "5001",
      "@BankDeptNumber": "1",
      "@DispatchNote":
        "Accident at I-10 Sawyer - Add 30 minutes to downtown destinations",
      "@SiteTitle": "Corp",
      "@PaymentGatewayID": "2",
      "@MName": "TEST Remit Company",
      "@MAddress": "Remit Address Here",
      "@MCity": "Houston",
      "@MState": "Tx",
      "@MZip": "77002",
      "@MCountry": "USA",
      "@MPhone": "281-812-3762",
      "@MEmail": "buddy@e-courier.com",
      "@LogoImageID": "3",
      "@SiteStatus": "A",
    },
    Customer: {
      "@CustomerID": "107",
      "@CustomerCode": "10011",
      "@Name": "AutoCustomer",
      "@Address": "1211 Dyberry Pl",
      "@City": "Honesdale",
      "@State": "PA",
      "@Zip": "18431",
      "@Country": "USA",
      "@Phone": "284.038.6466x1538",
      "@See": "Jessica Davidson",
      "@Room": "2D152",
      "@PName": "Kathryn Senor Elementary School",
      "@PAddress": "264 Overton Rd",
      "@PCity": "New Albany",
      "@PState": "PA",
      "@PackageTypeID": "0",
      "@PZip": "18833",
      "@PCountry": "USA",
      "@PPhone": "+12137402805",
      "@PSee": "Director",
      "@PRoom": "master",
      "@PAVSQuality": "-1",
      "@Service": "Regular",
      "@VehicleTypeID": "1",
      "@CreatedDate": "7/5/2022 10:39:31 PM",
      "@SiteID": "1",
      "@CustomerTypeID": "1",
      "@OrderPriorityID": "0",
      "@CustomerShipToUpdate": "True",
      "@SetSiteFlag": "1",
      "@AVSCheck": "-1",
      "@CustomerStatus": "A",
      "@SiteCode": "Corporate",
      "@CreditStatusID": "1",
      "@OkCreditStatus": "True",
      "@CreditBilling": "1",
      "@ShowSaveCustomerPaymentMethod": "9",
      "@DefaultDueTime": "0",
      CustomerBillingTypes: {
        "@BillingTypeID": "0",
        "@ShowSaveCustomerPaymentMethod": "9",
        BillingType: {
          "@BillingTypeID": "0",
          "@CreditCardDescription": "BillMe(Invoice)",
          "@PaymentTypeID": "0",
          "@PaymentTypeDescription": "BillMe",
          "@PaymentTenderTypeCode": "X",
          "@WebUserID": "-1",
        },
      },
    },
    Pieces: null,
    OrderEvents: {
      OrderEvent: [
        {
          "@OrderEventID": "291809",
          "@EventType": "Deleted",
          "@EventDateTime": "8/22/2022 10:34:26 PM",
          "@UserName": "automationtest",
          "@Note": "Status: N --> X {36786BF1-05B7-4F0F-90B3-F73B19D277D9}",
          "@EventSource": "",
          "@RefType": "OrderMain.OrderID",
          "@RefID": "6842",
        },
        {
          "@OrderEventID": "291808",
          "@EventType": "Deleted",
          "@EventDateTime": "8/22/2022 10:34:26 PM",
          "@UserName": "automationtest",
          "@Note": "Job: 6842 Status: N --> X",
          "@EventSource": "",
          "@RefType": "Job.JobID",
          "@RefID": "6800",
        },
        {
          "@OrderEventID": "291805",
          "@EventType": "Notify",
          "@EventDateTime": "8/22/2022 9:34:05 PM",
          "@UserName": "",
          "@Note":
            "6842 $150.00 --> From: helpdesk@e-courier.com To: Marc59@yahoo.com",
          "@EventSource": "",
        },
        {
          "@OrderEventID": "291804",
          "@EventType": "New",
          "@EventDateTime": "8/22/2022 9:34:05 PM",
          "@UserName": "automationtest",
          "@Note": "",
          "@EventSource": "",
        },
        {
          "@OrderEventID": "291803",
          "@EventType": "SaveOrder",
          "@EventDateTime": "8/22/2022 9:34:05 PM",
          "@UserName": "automationtest",
          "@Note":
            "{36786BF1-05B7-4F0F-90B3-F73B19D277D9} 6692 2022-08-22 23:34:05.361 dev001",
          "@EventSource": "",
        },
      ],
    },
  },
];
describe("downloadTextFile", () => {
  const date = moment(Date.now()).format("MMMddyyyy_hhmmss");

  it("should download the file", () => {
    const link: any = {
      click: jest.fn(),
    };
    jest.spyOn(document, "createElement").mockImplementation(() => link);
    exportUserInfo(mockdata, "6842");
    expect(link.className).toEqual("download-file");
    expect(link.download).toEqual(`Order_${6842}_${date}.text`);
    expect(link.click).toHaveBeenCalledTimes(1);
  });
});
